import Head from 'next/head';

import About from '../components/About';
import Skills from '../components/Skills';
import ComputerProjects from '../components/ComputerProjects';
import PhoneProjects from '../components/PhoneProjects';
import Contact from '../components/Contact';
import Navbar from '../components/Navbar';
import ComputerMain from '../components/ComputerMain';
import PhoneMain from '../components/PhoneMain';
import useMediaQuery from '../helpers/mediaQueries';

import { motion } from 'framer-motion';

export default function Home() {
  const isPhone = useMediaQuery('(max-width: 550px)');
  return (
    <motion.div exit={{ opacity: 0 }}>
      <Head>
        <title>Sandra Gufler | Fullstack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smiley.ico" />
      </Head>
      <Navbar />
      {!isPhone ? <ComputerMain /> : <PhoneMain />}
      <About className="pt-[7%]" />
      {!isPhone ? (
        <ComputerProjects className="pt-[7%]" />
      ) : (
        <PhoneProjects className="pt-[7%]" />
      )}
      <Skills className="pt-[7%]" />
      <Contact className="pt-[7%]" />
    </motion.div>
  );
}
