import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sandra Gufler | Fullstack developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/smiley.ico" />
      </Head>
      <Navbar />
      <Main />
    </div>
  );
};
